import {GameModel} from './GameModel.js';
import {EnhancedView,EnhancedController} from './Enhancements.js';
export class ClassroomModel extends GameModel{
prepareSeason(){super.prepareSeason();this.state.ruinsPending=false;this.state.currentRequiresRuins=false;}
drawNextCard(){super.drawNextCard();const s=this.state,card=this.cards.get(s.currentCardId);s.currentRequiresRuins=false;if(card.effect==='ruins')s.ruinsPending=true;else if(card.type==='exploration'&&s.ruinsPending){s.currentRequiresRuins=true;s.ruinsPending=false;}}
restoreState(value){super.restoreState(value);if(this.state.phase!=='setup'){this.state.ruinsPending=Boolean(this.state.ruinsPending);this.state.currentRequiresRuins=Boolean(this.state.currentRequiresRuins);}}
}
export class ClassroomView extends EnhancedView{
zoomable(card){const node=this.card(card);node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',`${card.name}, otevřít detail`);node.addEventListener('click',()=>this.zoom(card));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.zoom(card);}});return node;}
render(model,canUndo){super.render(model,canUndo);const s=model.state;if(!['exploring','seasonEnd'].includes(s.phase))return;const lower=this.root.querySelector('.lower');lower.replaceChildren();const zone=document.createElement('section');zone.className='play-zone';const strip=document.createElement('div');strip.className='strip';strip.setAttribute('aria-label','Historie odkrytých karet');for(const id of s.revealedThisSeason.slice(0,-1))strip.append(this.zoomable(model.cards.get(id)));if(!strip.children.length){const p=document.createElement('p');p.className='empty';p.textContent='Zde bude historie karet';strip.append(p);}const focus=document.createElement('div');focus.className='focus-area';const info=document.createElement('div');info.className='player-info';info.setAttribute('role','status');const card=model.cards.get(s.currentCardId);if(card)focus.append(this.zoomable(card));else{const p=document.createElement('p');p.className='empty';p.textContent='Otočte první kartu';focus.append(p);}const lines=[];if(card?.effect==='ruins'){lines.push('Zříceniny!');const timer=document.createElement('div');timer.className='countdown';timer.id='ruins-countdown';timer.textContent='Další karta za 5 s';info.append(timer);}if(card?.type==='ambush'){lines.push(`Předejte mapy ${card.direction==='P'?'doprava':'doleva'}.`,`Zakreslete nestvůry a vraťte mapy.`);if(s.ruinsPending)lines.push('Zříceniny platí pro následující průzkum.');}if(s.currentRequiresRuins)lines.push('Kresli přes zříceninu.','Pokud to nelze: volné 1 × 1 libovolným terénem.');const text=document.createElement('div');text.textContent=lines.join('\n\n');info.append(text);focus.append(info);zone.append(strip,focus);lower.append(zone);const summary=document.createElement('p');summary.className='summary';summary.textContent=`Odkryto ${s.revealedThisSeason.length} · Zbývá ${s.explorationDeck.length}`;lower.append(summary);document.querySelector('#notice').textContent=s.phase==='seasonEnd'?'Dokreslete kartu a přejděte k bodování.':'';requestAnimationFrame(()=>{strip.scrollLeft=strip.scrollWidth;});}
}
export class ClassroomController extends EnhancedController{
constructor(model,view){super(model,view);document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||document.querySelector('dialog[open]')||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;const next=['ArrowRight','ArrowDown','PageDown'].includes(e.key),back=['ArrowLeft','ArrowUp','Backspace','PageUp'].includes(e.key);if(!next&&!back)return;e.preventDefault();if(e.repeat||this.busy)return;if(next)this.perform();else this.undo();});window.addEventListener('pagehide',()=>this.stopTimer());}
stopTimer(){if(this.timer)clearInterval(this.timer);this.timer=null;}
render(){super.render();this.stopTimer();const s=this.model.state,card=this.model.cards.get(s.currentCardId);if(s.phase!=='exploring'||card?.effect!=='ruins')return;let remaining=5000,last=performance.now();this.timer=setInterval(()=>{const now=performance.now(),dt=now-last;last=now;const paused=document.hidden||Boolean(document.querySelector('dialog[open]'))||this.busy;if(!paused)remaining-=dt;const label=document.querySelector('#ruins-countdown');if(label)label.textContent=paused?`Odpočet pozastaven (${Math.max(1,Math.ceil(remaining/1000))} s)`:`Další karta za ${Math.max(0,Math.ceil(remaining/1000))} s`;if(remaining<=0&&!paused){this.stopTimer();this.perform();}},100);}
async perform(restart=false){if(this.busy)return;this.stopTimer();try{await super.perform(restart);}finally{if(!this.timer)this.render();}}
undo(){if(this.busy)return;this.stopTimer();super.undo();if(!this.timer)this.render();}
}
