import {PresentationView,PresentationController} from './Presentation.js';
import {ClassroomView} from './Classroom.js';
const style=document.createElement('style');style.textContent=`.focus-area.deck-stage{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);position:relative;gap:0;isolation:isolate;overflow:visible}.deck-stage>.current-panel,.deck-stage>.draw-panel{position:relative;min-width:0;min-height:0;display:flex;align-items:center;justify-content:center}.deck-stage .current-panel>.card,.deck-stage .draw-panel>.card{width:100%;height:100%;max-width:100%;object-fit:contain}.deck-stage .card img{width:100%;height:100%;object-fit:contain}.deck-stage .draw-panel>.player-info{position:absolute;inset:10px;z-index:2;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;pointer-events:none;background:rgba(20,28,22,.88);color:#fff;border-radius:10px;padding:14px;white-space:pre-line}.deck-stage .draw-panel>.player-info:empty{display:none}.deck-stage .deck-count{position:absolute;bottom:0;left:0;right:0;z-index:3;text-align:center;background:rgba(20,28,22,.9);color:#fff;padding:4px;font-size:16px}.deck-stage .page-shell{position:absolute;left:50%;top:0;bottom:0;width:50%;perspective:1200px;z-index:5;pointer-events:none}.deck-stage .page-plane{position:absolute;inset:0;transform-origin:left center;transform-style:preserve-3d}.deck-stage .page-plane>.card{position:absolute;inset:0;width:100%;height:100%;backface-visibility:visible}.deck-stage .page-plane>.page-front{transform:rotateY(180deg)}`;document.head.append(style);
export class DeckPresentationView extends PresentationView{
render(model,canUndo){const previous=this.lastSnapshot,s=model.state;ClassroomView.prototype.render.call(this,model,canUndo);this.lastSnapshot=model.snapshot();this.flipPromise=null;if(s.phase==='setup'){this.setup(model);return;}if(!['exploring','seasonEnd'].includes(s.phase))return;
const focus=this.root.querySelector('.focus-area');if(!focus)return;const original=focus.querySelector(':scope>.card'),info=focus.querySelector('.player-info');const current=document.createElement('div');current.className='current-panel';if(original)current.append(original);else{const empty=focus.querySelector('.empty');if(empty)current.append(empty);}const pile=document.createElement('div');pile.className='draw-panel';if(s.explorationDeck.length)pile.append(this.card({name:'Dobírací balíček průzkumu',front:'./assets/cards/pruzkum-zadek.png'}));const count=document.createElement('div');count.className='deck-count';count.textContent=`Zbývá ${s.explorationDeck.length} karet`;pile.append(count);if(info&&(info.querySelector('.countdown')||info.textContent.trim()))pile.append(info);focus.replaceChildren(current,pile);focus.classList.add('deck-stage');
const newlyDrawn=previous&&previous.phase==='exploring'&&s.revealedThisSeason.length===previous.revealedThisSeason.length+1&&s.currentCardId!==previous.currentCardId;if(!newlyDrawn||!original||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
const shell=document.createElement('div');shell.className='page-shell';const plane=document.createElement('div');plane.className='page-plane';plane.append(this.card({name:'Rub průzkumu',front:'./assets/cards/pruzkum-zadek.png'}));shell.append(plane);focus.append(shell);original.style.visibility='hidden';this.animating=true;
this.flipPromise=(async()=>{try{await plane.animate([{transform:'rotateY(0deg)'},{transform:'rotateY(-90deg)'}],{duration:300,easing:'ease-in',fill:'forwards'}).finished;plane.style.transform='rotateY(-90deg)';plane.getAnimations().forEach(a=>a.cancel());const face=this.card(model.cards.get(s.currentCardId));face.classList.add('page-front');plane.replaceChildren(face);await plane.animate([{transform:'rotateY(-90deg)'},{transform:'rotateY(-180deg)'}],{duration:300,easing:'ease-out',fill:'forwards'}).finished;}finally{shell.remove();original.style.removeProperty('visibility');this.animating=false;}})().catch(()=>{});
}
}
export class DeckPresentationController extends PresentationController{}
