import {PresentationView,PresentationController} from './Presentation.js';
import {ClassroomView} from './Classroom.js';
const style=document.createElement('style');style.textContent=`.focus-area.deck-stage{display:flex;position:relative;gap:0;align-items:center;justify-content:center;isolation:isolate;overflow:visible}.deck-stage>.current-panel,.deck-stage>.draw-panel{position:relative;min-width:0;flex:0 1 auto;max-width:50%;display:flex;align-items:center;justify-content:center}.deck-stage .current-panel>.card,.deck-stage .draw-panel>.card{width:100%;height:100%;max-width:100%}.deck-stage .card img{width:100%;height:100%;object-fit:contain}.deck-stage .draw-panel>.player-info{position:absolute;inset:8px;z-index:2;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;pointer-events:none;background:rgba(20,28,22,.88);color:#fff;border-radius:10px;padding:10px;white-space:pre-line;overflow:auto}.deck-stage .draw-panel>.player-info:empty{display:none}.deck-stage .page-shell{position:absolute;perspective:1200px;z-index:5;pointer-events:none}.deck-stage .page-plane{position:absolute;inset:0;transform-origin:left center;transform-style:preserve-3d}.deck-stage .page-plane>.card{position:absolute;inset:0;width:100%;height:100%;backface-visibility:visible}.deck-stage .page-plane>.page-front{transform:rotateY(180deg)}`;document.head.append(style);
export class DeckPresentationView extends PresentationView{
render(model,canUndo){const previous=this.lastSnapshot,s=model.state;ClassroomView.prototype.render.call(this,model,canUndo);this.lastSnapshot=model.snapshot();this.flipPromise=null;if(s.phase==='setup'){this.setup(model);return;}if(!['exploring','seasonEnd'].includes(s.phase))return;
const focus=this.root.querySelector('.focus-area');if(!focus)return;const original=focus.querySelector(':scope>.card'),info=focus.querySelector('.player-info');let probe=original;if(!probe){probe=this.zoomable(model.catalog.exploration[0]);focus.prepend(probe);}const size=probe.getBoundingClientRect();if(!original)probe.remove();const current=document.createElement('div');current.className='current-panel';current.style.width=`${size.width}px`;current.style.height=`${size.height}px`;if(original)current.append(original);else{const empty=focus.querySelector('.empty');if(empty)current.append(empty);}const pile=document.createElement('div');pile.className='draw-panel';pile.style.width=`${size.width}px`;pile.style.height=`${size.height}px`;if(s.explorationDeck.length)pile.append(this.card({name:'Dobírací balíček průzkumu',front:'./assets/cards/pruzkum-zadek.png'}));if(info&&(info.querySelector('.countdown')||info.textContent.trim()))pile.append(info);focus.replaceChildren(current,pile);focus.classList.add('deck-stage');
const newlyDrawn=previous&&previous.phase==='exploring'&&s.revealedThisSeason.length===previous.revealedThisSeason.length+1&&s.currentCardId!==previous.currentCardId;if(!newlyDrawn||!original||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
const bounds=focus.getBoundingClientRect(),deckBounds=pile.getBoundingClientRect();const shell=document.createElement('div');shell.className='page-shell';shell.style.left=`${deckBounds.left-bounds.left-focus.clientLeft+focus.scrollLeft}px`;shell.style.top=`${deckBounds.top-bounds.top-focus.clientTop+focus.scrollTop}px`;shell.style.width=`${deckBounds.width}px`;shell.style.height=`${deckBounds.height}px`;const plane=document.createElement('div');plane.className='page-plane';plane.append(this.card({name:'Rub průzkumu',front:'./assets/cards/pruzkum-zadek.png'}));shell.append(plane);focus.append(shell);original.style.visibility='hidden';this.animating=true;
this.flipPromise=(async()=>{try{await plane.animate([{transform:'rotateY(0deg)'},{transform:'rotateY(-90deg)'}],{duration:300,easing:'ease-in',fill:'forwards'}).finished;plane.style.transform='rotateY(-90deg)';plane.getAnimations().forEach(a=>a.cancel());const face=this.card(model.cards.get(s.currentCardId));face.classList.add('page-front');plane.replaceChildren(face);await plane.animate([{transform:'rotateY(-90deg)'},{transform:'rotateY(-180deg)'}],{duration:300,easing:'ease-out',fill:'forwards'}).finished;}finally{shell.remove();original.style.removeProperty('visibility');this.animating=false;}})().catch(()=>{});
}
}
export class DeckPresentationController extends PresentationController{}
