import {GameView} from './GameView.js';
import {GameController} from './GameController.js';
export class EnhancedView extends GameView{
card(card){const node=super.card(card);node.querySelector('.time')?.remove();return node;}
render(model,canUndo){super.render(model,canUndo);const scoring=model.state.phase==='scoring';this.root.classList.toggle('scoring-mode',scoring);if(!scoring)return;const lower=this.root.querySelector('.lower');lower.replaceChildren();const pair=document.createElement('div');pair.className='scoring-pair';for(const slot of model.seasons[model.state.seasonIndex].scoringSlots){const card=model.cards.get(model.state.scoringAssignments[slot]),node=this.card(card);node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',`Výnos ${slot}, otevřít detail`);node.addEventListener('click',()=>this.zoom(card));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.zoom(card);}});pair.append(node);}lower.append(pair);const text=document.createElement('p');text.className='summary';text.textContent='Bodované karty · kliknutím otevřete detail';lower.append(text);}
confirmRestart(){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='confirm-game';dialog.setAttribute('aria-label','Potvrdit novou hru');const text=document.createElement('p');text.textContent='Zahájit novou hru? Rozehranou partii tím opustíte.';const actions=document.createElement('div');actions.className='actions';const cancel=document.createElement('button');cancel.textContent='Pokračovat ve hře';cancel.autofocus=true;const yes=document.createElement('button');yes.textContent='Nová hra';let approved=false;cancel.addEventListener('click',()=>dialog.close());yes.addEventListener('click',()=>{approved=true;dialog.close();});dialog.addEventListener('close',()=>{dialog.remove();resolve(approved);},{once:true});actions.append(cancel,yes);dialog.append(text,actions);document.body.append(dialog);dialog.showModal();});}
}
export class EnhancedController extends GameController{
async perform(restart=false){if(this.busy)return;this.busy=true;try{const phase=this.model.state.phase;if(restart&&phase!=='setup'&&phase!=='finished'&&!await this.view.confirmRestart())return;if(!restart){super.perform(false);return;}const before=this.model.snapshot();try{this.model.startNewGame();this.history.push(before);this.history=this.history.slice(-100);this.view.message('');this.save();this.render();}catch(error){this.model.restoreState(before);this.view.message(error.message);}}finally{this.busy=false;}}
}
export async function preload(catalog,seasons,edicts){
const urls=[...new Set([...catalog.scoring,...catalog.exploration,...catalog.ambush,...seasons,...Object.values(edicts)].flatMap(c=>[c.front,c.back]).filter(Boolean))];
const root=document.querySelector('#app'),panel=document.createElement('section');panel.className='loader';const heading=document.createElement('h2');heading.textContent='Načítání obrázků hry';const progress=document.createElement('progress');progress.max=urls.length;progress.value=0;const text=document.createElement('p');panel.append(heading,progress,text);root.replaceChildren(panel);const ready=new Map();let pending=urls;
while(pending.length){let cursor=0;const failed=[];const load=async url=>{const image=new Image();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{image.onload=null;image.onerror=null;reject(new Error('timeout'));},30000);image.onload=()=>{clearTimeout(timer);resolve();};image.onerror=()=>{clearTimeout(timer);reject(new Error('load'));};image.src=url;});if(image.decode)await image.decode();return image;};
await Promise.all(Array.from({length:Math.min(6,pending.length)},async()=>{while(cursor<pending.length){const url=pending[cursor++];try{ready.set(url,await load(url));}catch{failed.push(url);}progress.value=ready.size;text.textContent=`Připraveno ${ready.size} z ${urls.length}`;}}));
if(!failed.length)break;text.textContent=`Nepodařilo se načíst ${failed.length} obrázků.\n${failed.join('\n')}\nHra začne až po jejich načtení.`;const retry=document.createElement('button');retry.textContent='Zkusit načítání znovu';panel.append(retry);await new Promise(resolve=>retry.addEventListener('click',resolve,{once:true}));retry.remove();pending=failed;
}return [...ready.values()];
}
