import {edicts} from './data.js';
export class GameView{
constructor(){this.root=document.querySelector('#app');this.action=document.querySelector('#action');this.dialog=document.querySelector('#zoom');document.querySelector('#close').addEventListener('click',()=>this.dialog.close());this.dialog.addEventListener('click',e=>{if(e.target===this.dialog){const r=this.dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.dialog.close();}});}
card(card){const node=document.createElement('div');node.className='card';node.title=card.name;if(card.front){const img=document.createElement('img');img.src=card.front;img.alt=card.name;img.addEventListener('error',()=>{img.remove();node.classList.add('fallback');node.append(document.createTextNode(card.name));},{once:true});node.append(img);}else{node.classList.add('fallback');node.textContent=card.name;}if(Number.isFinite(card.time)){const t=document.createElement('span');t.className='time';t.textContent=card.time;t.setAttribute('aria-label',`Čas ${card.time}`);node.append(t);}return node;}
zoom(card){document.querySelector('#detail').replaceChildren(this.card(card));if(!this.dialog.open)this.dialog.showModal();}
render(model,canUndo){const s=model.state;this.root.replaceChildren();document.querySelector('#undo').disabled=!canUndo;this.action.textContent=({setup:'Nová hra',exploring:'Další karta',seasonEnd:'Přejít k bodování',scoring:s.seasonIndex===3?'Ukončit hru':'Zahájit další období',finished:'Nová hra'})[s.phase];const notice=document.querySelector('#notice');notice.textContent='';if(s.phase==='setup'){const p=document.createElement('p');p.className='empty';p.textContent='Spusťte novou hru';this.root.append(p);return;}
const season=model.seasons[s.seasonIndex],top=document.createElement('section');top.className='top';const sp=document.createElement('section');sp.className='season';sp.append(this.card(season));const progress=document.createElement('div');progress.className='progress';progress.textContent=`${s.elapsedTime} / ${season.limit}`;sp.append(progress);top.append(sp);
['A','B','C','D'].forEach((slot,i)=>{const upper=document.createElement('div');upper.className='slot';upper.style.gridColumn=i+2;upper.style.gridRow=1;upper.append(this.card(edicts[slot]));top.append(upper);const lower=document.createElement('div');lower.className='slot';lower.style.gridColumn=i+2;lower.style.gridRow=2;const card=model.cards.get(s.scoringAssignments[slot]),node=this.card(card),active=season.scoringSlots.includes(slot);node.classList.add('scoring',active?'active':'inactive');node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',`${slot}: ${card.name}, ${active?'boduje se':'nyní se neboduje'}, otevřít detail`);node.addEventListener('click',()=>this.zoom(card));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.zoom(card);}});lower.append(node);top.append(lower);});this.root.append(top);
const lower=document.createElement('section');lower.className='lower';const strip=document.createElement('div');strip.className='strip';strip.setAttribute('aria-label','Odkryté karty');for(const id of s.revealedThisSeason)strip.append(this.card(model.cards.get(id)));if(!s.revealedThisSeason.length){const p=document.createElement('p');p.className='empty';p.textContent='Otočte první kartu';strip.append(p);}lower.append(strip);const summary=document.createElement('p');summary.className='summary';summary.textContent=`Odkryto ${s.revealedThisSeason.length} · Zbývá ${s.explorationDeck.length}`;lower.append(summary);this.root.append(lower);requestAnimationFrame(()=>{strip.scrollLeft=strip.scrollWidth;});
if(s.phase==='scoring')notice.textContent=`Bodování ${season.scoringSlots.join(' + ')}\n+1 za každou minci\n−1 za každé prázdné pole sousedící s nestvůrami. Každé pole jen jednou.`;else if(s.phase==='finished')notice.textContent='Konec hry — sečtěte výsledky všech období.';else{const lines=[];if(s.phase==='seasonEnd')lines.push('Dokreslete poslední kartu, potom přejděte k bodování.');const card=model.cards.get(s.currentCardId);if(card?.type==='ambush')lines.push(`Předejte mapy ${card.direction==='P'?'doprava':'doleva'}. Po zakreslení je vraťte majitelům.`);if(s.currentRequiresRuins)lines.push('Zakresli přes alespoň jedno políčko zřícenin. Pokud to nelze nebo nemáš volnou zříceninu: volné 1 × 1 libovolným terénem.');else if(s.ruinsPending)lines.push('Zříceniny čekají na další běžnou kartu průzkumu.');notice.textContent=lines.join('\n\n');}}
message(text){document.querySelector('#message').textContent=text;}
}
